# AI Disclosure: Code comments were generated by AI

import os
import random
import json
import csv


class RandomFileSelector:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "file_path": ("STRING", {"default": "examples/colors.txt"}),
                # We use "seed" to make the random choice reproducible
                "seed": ("INT", {"default": 0, "min": 0, "max": 0xffffffffffffffff}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("selected_item",)
    FUNCTION = "get_random_item"
    CATEGORY = "Utils/Random"

    def get_random_item(self, file_path, seed):
        # . Set the seed for reproducibility
        # This ensures if you load an old workflow, you get the same random result
        random.seed(seed)

        if not os.path.exists(file_path):
            return (f"Error: File not found at {file_path}",)

        _, ext = os.path.splitext(file_path)
        ext = ext.lower()

        try:
            items = []

            # --- PARSE TXT ---
            if ext == '.txt':
                with open(file_path, 'r', encoding='utf-8') as f:
                    # Read lines and strip whitespace
                    items = [line.strip() for line in f if line.strip()]

            # --- PARSE CSV ---
            elif ext == '.csv':
                with open(file_path, 'r', encoding='utf-8') as f:
                    reader = csv.reader(f)
                    # Flatten the CSV: Treat every cell in every row as a potential item
                    # OR: You could choose to just take the first column.
                    # Here, I'm joining the row into a string for flexibility.
                    items = [", ".join(row) for row in reader if row]

            # --- PARSE JSON ---
            elif ext == '.json':
                with open(file_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    # If it's a list ["a", "b"], pick from it
                    if isinstance(data, list):
                        items = [str(x) for x in data]
                    # If it's a dict {"color": "red"}, pick a random VALUE
                    elif isinstance(data, dict):
                        items = [str(v) for v in data.values()]
                    else:
                        return ("Error: JSON root must be a list or dictionary",)

            else:
                return (f"Error: Unsupported file extension {ext}",)

            if not items:
                return ("Error: File is empty",)

            # 4. Select the item
            selected = random.choice(items)
            return (selected,)

        except Exception as e:
            return (f"Error parsing file: {str(e)}",)